/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wmdcnjgtsppftrofaqqa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZGNuamd0c3BwZnRyb2ZhcXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxMTYwMjIsImV4cCI6MjA4MjY5MjAyMn0.ePMQxB16I3nm_db5AAi-cg-QGaSwIwXxtmNa6r7aMPk"