/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const fallbackProjectId = "wmdcnjgtsppftrofaqqa";
const fallbackAnonKey =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZGNuamd0c3BwZnRyb2ZhcXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxMTYwMjIsImV4cCI6MjA4MjY5MjAyMn0.ePMQxB16I3nm_db5AAi-cg-QGaSwIwXxtmNa6r7aMPk";

const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;

export const projectId = envSupabaseUrl
	? envSupabaseUrl.replace(/^https:\/\//, "").split(".")[0]
	: fallbackProjectId;

export const publicAnonKey =
	(import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) || fallbackAnonKey;
