export {
  arrivalActionPhrases,
  arrivalApproachPhrases,
  continueActionPhrases,
  departureActionPhrases,
  endOfRoadActionPhrases,
  forkActionPhrases,
  keepActionPhrases,
  mergeActionPhrases,
  offRampActionPhrases,
  onRampActionPhrases,
  roadFallbacks,
  roundaboutExitPhrases,
  roundaboutNoExitPhrases,
  sharpTurnActionPhrases,
  slightTurnActionPhrases,
  straightContinuePhrases,
  turnActionPhrases,
  uTurnActionPhrases,
} from "./routeVoiceActionPhrases";

export const leadInPhrases = [
  "Heads up,",
  "Coming up,",
  "Next move,",
  "Route update,",
  "Plan ahead,",
  "Keep this lane,",
  "Watch for this,",
  "Next turn,",
  "Get ready,",
  "Ahead,",
  "Road ahead,",
  "Stay alert,",
];

export const urgencyLeadInPhrases = [
  "Now,",
  "Immediately,",
  "Sharp attention,",
  "Act now,",
  "Right here,",
  "Move now,",
  "Turn now,",
  "This is it,",
  "Your turn is here,",
  "Execute now,",
  "Turn immediately,",
  "This is your turn,",
];

export const distanceUrgentPhrases = [
  "now",
  "right now",
  "immediately",
  "at this moment",
  "right here",
  "this instant",
  "on this spot",
  "act fast",
  "this is it",
  "take it now",
];

export const distanceClosePhrases = [
  "right away",
  "in just a moment",
  "very soon",
  "almost immediately",
  "in a beat",
  "coming up now",
  "in a short distance",
  "just ahead",
  "moments away",
  "coming into view",
  "in a brief stretch",
  "very shortly",
  "around the corner",
  "in seconds",
];

export const distanceNearPhrases = [
  "soon",
  "in a short stretch",
  "up ahead",
  "in the next block",
  "after this short segment",
  "just ahead",
  "in a moment",
  "before long",
  "in a short while",
  "within the block",
  "in the near distance",
  "after a little ways",
  "a short way ahead",
  "coming up shortly",
];

export const distanceFarPhrases = [
  "in about half a mile",
  "further up the road",
  "after some distance",
  "in a while",
  "well ahead",
  "down the road",
  "a good way ahead",
  "in the distance",
  "after this stretch",
];
