export const leadInPhrases = [
  "Heads up,",
  "Coming up,",
  "Next move,",
  "Route update,",
  "Navigation cue,",
  "Plan ahead,",
  "Stay with this lane,",
  "Keep this flow,",
  "Watch for this,",
  "Note ahead,",
  "Next turn,",
  "Route says,",
  "Get ready,",
  "Preparing for the next step,",
  "Guidance update,",
  "On your navigate,",
  "Road ahead,",
  "Routing note,",
  "Steady pace,",
  "Stay alert,",
];

export const urgencyLeadInPhrases = [
  "Now,",
  "Immediately,",
  "Sharp attention,",
  "Act now,",
  "Right here,",
  "Move now,",
  "Turn now,",
  "This is it,",
  "Your turn is here,",
  "Execute now,",
  "Turn immediately,",
  "This is your turn,",
];

export const distanceUrgentPhrases = [
  "now",
  "right now",
  "immediately",
  "at this moment",
  "right here",
  "this instant",
  "on this spot",
  "act fast",
  "this is it",
  "take it now",
];

export const distanceClosePhrases = [
  "right away",
  "in just a moment",
  "very soon",
  "almost immediately",
  "in a beat",
  "coming up now",
  "in a short distance",
  "just ahead",
  "moments away",
  "coming into view",
  "in a brief stretch",
  "very shortly",
  "around the corner",
  "in seconds",
];

export const distanceNearPhrases = [
  "soon",
  "in a short stretch",
  "up ahead",
  "in the next block",
  "after this short segment",
  "just ahead",
  "in a moment",
  "before long",
  "in a short while",
  "within the block",
  "in the near distance",
  "after a little ways",
  "a short way ahead",
  "coming up shortly",
];

export const distanceFarPhrases = [
  "after a longer stretch",
  "once you continue ahead",
  "further up the route",
  "after you stay on this road",
  "once you pass the next segment",
  "after this run",
  "in a while",
  "after a good stretch",
  "further along",
  "once you've covered more ground",
  "when you've gone a bit further",
  "after traveling a ways",
  "after a longer drive",
  "well ahead of you",
];

export const departureActionPhrases = [
  "head out on",
  "start by taking",
  "begin on",
  "roll out onto",
  "set off via",
  "kick off the route on",
  "leave here on",
  "begin your drive on",
  "depart via",
  "start your journey on",
  "head north on",
  "launch the route on",
  "let's get going on",
  "your route begins on",
  "pull out onto",
  "the route starts on",
  "first leg is",
  "starting road is",
];

export const arrivalActionPhrases = [
  "you are arriving at",
  "you have reached",
  "destination is here:",
  "arrive at",
  "this is your stop:",
  "you are now at",
  "you made it to",
  "final destination:",
  "you have arrived at",
  "welcome to",
  "journey ends at",
  "your stop is",
  "you are at your destination,",
  "arrival confirmed at",
  "the route end is",
  "you have reached your target:",
  "drop-off point:",
  "end of navigation at",
];

export const arrivalApproachPhrases = [
  "approaching your destination,",
  "coming up on your destination,",
  "destination is close now,",
  "within range of your stop,",
  "nearly there,",
  "your stop is just ahead,",
  "almost at destination,",
  "final approach to your stop,",
  "getting very close to the destination,",
  "arrival is near at",
  "almost at your destination,",
  "you are closing in on",
];

export const continueActionPhrases = [
  "continue on",
  "stay on",
  "keep following",
  "proceed along",
  "remain on",
  "keep moving on",
  "hold your line on",
  "carry on via",
  "stay the course on",
  "keep straight on",
  "press forward on",
  "cruise ahead on",
  "maintain your direction on",
  "track forward on",
  "keep your heading on",
  "advance along",
  "settle in on",
  "drive ahead on",
];

export const straightContinuePhrases = [
  "go straight on",
  "continue straight on",
  "drive straight ahead on",
  "proceed straight along",
  "keep heading straight on",
  "stay straight on",
  "maintain direction, straight on",
  "forward on",
  "head straight along",
  "arrow-straight on",
  "no turns, straight on",
  "hold it straight on",
];

export const turnActionPhrases = [
  "turn {modifier} onto",
  "make a {modifier} turn onto",
  "take a {modifier} onto",
  "go {modifier} onto",
  "swing {modifier} onto",
  "transition {modifier} onto",
  "move {modifier} onto",
  "angle {modifier} onto",
  "hook {modifier} onto",
  "bear {modifier} onto",
  "twist {modifier} onto",
  "cut {modifier} onto",
  "{modifier} turn onto",
  "bend {modifier} onto",
  "point {modifier} and get onto",
  "take the {modifier} turn onto",
  "make your {modifier} onto",
  "rotate {modifier} onto",
];

export const sharpTurnActionPhrases = [
  "take a sharp {modifier} turn onto",
  "make a tight {modifier} onto",
  "execute a hard {modifier} onto",
  "take the sharp {modifier} onto",
  "hard {modifier} onto",
  "sharp {modifier} — turn onto",
  "tight corner {modifier} onto",
  "very sharp {modifier} here — onto",
];

export const slightTurnActionPhrases = [
  "bear slightly {modifier} onto",
  "veer slightly {modifier} onto",
  "ease slightly {modifier} onto",
  "drift slightly {modifier} onto",
  "angle slightly {modifier} onto",
  "gentle {modifier} curve onto",
  "soft {modifier} turn onto",
  "light {modifier} here onto",
];

export const uTurnActionPhrases = [
  "make a U-turn when it is safe",
  "perform a U-turn ahead",
  "take a U-turn",
  "turn around at the next opportunity",
  "execute a U-turn here",
  "reverse direction — U-turn",
  "U-turn recommended at the next safe spot",
  "turn back the way you came",
  "do a U-turn up ahead",
  "legal U-turn ahead",
  "flip your direction via U-turn",
  "make a full turnaround",
];

export const keepActionPhrases = [
  "keep {modifier} on",
  "stay {modifier} on",
  "use the {modifier} lane on",
  "move to the {modifier} lane on",
  "hold {modifier} on",
  "stay in the {modifier} lane on",
  "keep your position {modifier} on",
  "track {modifier} on",
  "stay over {modifier} on",
  "hug the {modifier} side on",
  "favor the {modifier} lane on",
  "position yourself {modifier} on",
];

export const mergeActionPhrases = [
  "merge {modifier} onto",
  "blend {modifier} onto",
  "join {modifier} onto",
  "enter {modifier} onto",
  "flow {modifier} onto",
  "ease {modifier} onto",
  "merge over {modifier} onto",
  "continue by merging {modifier} onto",
  "slip {modifier} onto",
  "weave {modifier} onto",
  "pull {modifier} onto",
  "glide {modifier} onto",
  "slide {modifier} into",
  "work {modifier} onto",
  "transition over {modifier} onto",
  "navigate {modifier} onto",
  "smoothly merge {modifier} onto",
  "time your merge {modifier} onto",
];

export const onRampActionPhrases = [
  "take the on-ramp {modifier} toward",
  "use the on-ramp {modifier} for",
  "enter via the on-ramp {modifier} toward",
  "take the ramp {modifier} toward",
  "join using the on-ramp {modifier} toward",
  "follow the on-ramp {modifier} toward",
  "use the feeder ramp {modifier} toward",
  "move onto the ramp {modifier} toward",
  "accelerate up the on-ramp {modifier} toward",
  "enter the freeway via the ramp {modifier} toward",
  "use the entry ramp {modifier} toward",
  "hit the on-ramp {modifier} toward",
  "access the highway via the ramp {modifier} toward",
  "get on from the ramp {modifier} toward",
  "catch the on-ramp {modifier} toward",
  "ramp up {modifier} toward",
  "enter at the on-ramp {modifier} toward",
  "use the slip road {modifier} toward",
];

export const offRampActionPhrases = [
  "take the off-ramp {modifier} toward",
  "use the exit ramp {modifier} toward",
  "peel off {modifier} toward",
  "exit {modifier} toward",
  "leave via the off-ramp {modifier} toward",
  "follow the exit ramp {modifier} toward",
  "take the ramp out {modifier} toward",
  "move onto the off-ramp {modifier} toward",
  "take the exit {modifier} toward",
  "use the freeway exit {modifier} toward",
  "leave the highway {modifier} toward",
  "pull off {modifier} toward",
  "exit at the ramp {modifier} toward",
  "decelerate onto the ramp {modifier} toward",
  "get off at {modifier} toward",
  "slip off {modifier} toward",
  "leave the current road {modifier} toward",
  "follow the exit slip {modifier} toward",
];

export const forkActionPhrases = [
  "keep {modifier} toward",
  "bear {modifier} toward",
  "at the split, stay {modifier} toward",
  "follow the fork {modifier} toward",
  "take the {modifier} branch toward",
  "hold {modifier} at the fork toward",
  "track {modifier} toward",
  "choose the fork {modifier} toward",
  "at the fork, go {modifier} toward",
  "veer {modifier} at the split toward",
  "stay on the {modifier} path toward",
  "road splits here — stay {modifier} toward",
  "at the Y, go {modifier} toward",
  "take the {modifier} option toward",
  "the route forks — choose {modifier} toward",
  "follow the {modifier} road toward",
  "stay on your {modifier} side toward",
  "lean {modifier} at the junction toward",
];

export const endOfRoadActionPhrases = [
  "at the end of the road, turn {modifier}",
  "when this road ends, go {modifier}",
  "at road end, take a {modifier}",
  "at the T, turn {modifier}",
  "road terminates ahead, turn {modifier}",
  "at the end, swing {modifier}",
  "as this road closes, go {modifier}",
  "end of segment ahead, turn {modifier}",
  "road ends here — take a {modifier}",
  "at the dead end, go {modifier}",
  "when the road stops, turn {modifier}",
  "T-intersection ahead — go {modifier}",
  "this road terminates — choose {modifier}",
  "at the road's terminus, turn {modifier}",
  "dead-end junction — take the {modifier}",
  "the road ends ahead — swing {modifier}",
  "road closes — head {modifier}",
  "the current segment ends — go {modifier}",
];

export const roundaboutNoExitPhrases = [
  "take the roundabout",
  "enter the roundabout",
  "go through the roundabout",
  "use the roundabout",
  "follow the roundabout",
  "continue via the roundabout",
  "join the roundabout",
  "move through the roundabout",
  "navigate the roundabout",
  "circle through the roundabout",
  "enter and exit the roundabout",
  "use the traffic circle",
  "use the rotary",
  "follow the circle",
  "pass through the roundabout",
  "loop through the roundabout",
  "traverse the roundabout",
  "work through the roundabout",
];

export const roundaboutExitPhrases = [
  "take the roundabout and use exit {exit}",
  "enter the roundabout, then take exit {exit}",
  "at the roundabout, continue to exit {exit}",
  "use the roundabout and leave at exit {exit}",
  "follow the roundabout to exit {exit}",
  "go through the roundabout and take exit {exit}",
  "take roundabout exit {exit}",
  "at the circle, take exit {exit}",
  "enter the circle and leave at exit {exit}",
  "navigate the roundabout to exit {exit}",
  "circle around to take exit {exit}",
  "count to exit {exit} inside the roundabout",
  "at the traffic circle, leave at exit {exit}",
  "use the rotary and take exit {exit}",
  "enter the roundabout and count off to exit {exit}",
  "take the ring road to exit {exit}",
  "at this roundabout, stay on until exit {exit}",
  "round it and take exit {exit}",
];

export const roadFallbacks = [
  "the current road",
  "this road",
  "the active route",
  "the current segment",
  "the roadway ahead",
  "this corridor",
  "the route ahead",
  "this stretch",
  "the upcoming road",
  "the next stretch",
  "the present road",
  "this lane",
  "the onward road",
  "the road before you",
];
