import type { Coordinates } from "../../types/mapDomain";

export type AtlantaHubFocus =
  | "collision"
  | "luxury"
  | "pdr"
  | "ev"
  | "fleet"
  | "refinish"
  | "hail"
  | "claims";

export type AtlantaHubSeed = {
  id: number;
  name: string;
  address: string;
  city: string;
  zipCode: string;
  coordinates: Coordinates;
  focus: AtlantaHubFocus;
  serviceArea: string;
};

export const ATLANTA_HUB_IMAGES = [
  "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1666919643134-d97687c1826c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
];

export const ATLANTA_HUB_SEEDS: AtlantaHubSeed[] = [
  {
    id: 101,
    name: "Downtown Atlanta Dent Center",
    address: "55 Trinity Ave SW",
    city: "Atlanta",
    zipCode: "30303",
    coordinates: { latitude: 33.749, longitude: -84.388 },
    focus: "claims",
    serviceArea: "Downtown core + Grady corridor",
  },
  {
    id: 102,
    name: "Midtown Precision Collision",
    address: "950 Peachtree St NE",
    city: "Atlanta",
    zipCode: "30309",
    coordinates: { latitude: 33.7825, longitude: -84.3875 },
    focus: "collision",
    serviceArea: "Midtown + Piedmont Park beltline",
  },
  {
    id: 103,
    name: "Buckhead Luxury Bodyworks",
    address: "3060 Peachtree Rd NW",
    city: "Atlanta",
    zipCode: "30305",
    coordinates: { latitude: 33.8392, longitude: -84.3794 },
    focus: "luxury",
    serviceArea: "Buckhead + Lenox luxury corridor",
  },
  {
    id: 104,
    name: "Old Fourth Ward PDR Studio",
    address: "680 North Ave NE",
    city: "Atlanta",
    zipCode: "30308",
    coordinates: { latitude: 33.7681, longitude: -84.3687 },
    focus: "pdr",
    serviceArea: "O4W + Inman Park",
  },
  {
    id: 105,
    name: "West End Claims Repair Hub",
    address: "1075 Lee St SW",
    city: "Atlanta",
    zipCode: "30310",
    coordinates: { latitude: 33.7457, longitude: -84.4128 },
    focus: "claims",
    serviceArea: "West End + Adair Park",
  },
  {
    id: 106,
    name: "East Atlanta Frame & Paint",
    address: "1300 Glenwood Ave SE",
    city: "Atlanta",
    zipCode: "30316",
    coordinates: { latitude: 33.7413, longitude: -84.3459 },
    focus: "refinish",
    serviceArea: "East Atlanta + Grant Park",
  },
  {
    id: 107,
    name: "Decatur ADAS & EV Center",
    address: "125 Clairemont Ave",
    city: "Decatur",
    zipCode: "30030",
    coordinates: { latitude: 33.7748, longitude: -84.2963 },
    focus: "ev",
    serviceArea: "Decatur + DeKalb urban core",
  },
  {
    id: 108,
    name: "Sandy Springs Direct Repair",
    address: "6400 Roswell Rd",
    city: "Sandy Springs",
    zipCode: "30328",
    coordinates: { latitude: 33.9304, longitude: -84.3733 },
    focus: "collision",
    serviceArea: "Sandy Springs + North Springs",
  },
  {
    id: 109,
    name: "Brookhaven Express Auto Body",
    address: "3911 Peachtree Rd NE",
    city: "Brookhaven",
    zipCode: "30319",
    coordinates: { latitude: 33.8601, longitude: -84.3394 },
    focus: "claims",
    serviceArea: "Brookhaven + Chastain",
  },
  {
    id: 110,
    name: "Chamblee Calibration Garage",
    address: "5200 Peachtree Blvd",
    city: "Chamblee",
    zipCode: "30341",
    coordinates: { latitude: 33.8925, longitude: -84.2988 },
    focus: "ev",
    serviceArea: "Chamblee + Buford Highway",
  },
  {
    id: 111,
    name: "Doraville Fleet & Commercial",
    address: "5800 Buford Hwy NE",
    city: "Doraville",
    zipCode: "30340",
    coordinates: { latitude: 33.9029, longitude: -84.28 },
    focus: "fleet",
    serviceArea: "Doraville + I-285 logistics belt",
  },
  {
    id: 112,
    name: "Tucker Dent & Glass Hub",
    address: "2325 Main St",
    city: "Tucker",
    zipCode: "30084",
    coordinates: { latitude: 33.8545, longitude: -84.2171 },
    focus: "pdr",
    serviceArea: "Tucker + Northlake",
  },
  {
    id: 113,
    name: "Stone Mountain Storm Repair",
    address: "875 Main St",
    city: "Stone Mountain",
    zipCode: "30083",
    coordinates: { latitude: 33.8082, longitude: -84.1702 },
    focus: "hail",
    serviceArea: "Stone Mountain + east DeKalb",
  },
  {
    id: 114,
    name: "College Park Quick Intake Collision",
    address: "3717 Main St",
    city: "College Park",
    zipCode: "30337",
    coordinates: { latitude: 33.6534, longitude: -84.4494 },
    focus: "collision",
    serviceArea: "College Park + airport south",
  },
  {
    id: 115,
    name: "Hapeville Airport Corridor Auto Body",
    address: "620 N Central Ave",
    city: "Hapeville",
    zipCode: "30354",
    coordinates: { latitude: 33.6596, longitude: -84.4107 },
    focus: "claims",
    serviceArea: "Hapeville + airport loop",
  },
  {
    id: 116,
    name: "East Point Claims Concierge",
    address: "2793 Main St",
    city: "East Point",
    zipCode: "30344",
    coordinates: { latitude: 33.6796, longitude: -84.4394 },
    focus: "claims",
    serviceArea: "East Point + Camp Creek",
  },
  {
    id: 117,
    name: "Smyrna Refinish Works",
    address: "1275 Spring Rd SE",
    city: "Smyrna",
    zipCode: "30080",
    coordinates: { latitude: 33.883, longitude: -84.5144 },
    focus: "refinish",
    serviceArea: "Smyrna + Vinings",
  },
  {
    id: 118,
    name: "Marietta Frame & Dent Lab",
    address: "205 Lawrence St NE",
    city: "Marietta",
    zipCode: "30060",
    coordinates: { latitude: 33.9526, longitude: -84.5499 },
    focus: "collision",
    serviceArea: "Marietta square + south Cobb",
  },
  {
    id: 119,
    name: "Kennesaw Collision Network",
    address: "2829 Cherokee St NW",
    city: "Kennesaw",
    zipCode: "30144",
    coordinates: { latitude: 34.0234, longitude: -84.6155 },
    focus: "fleet",
    serviceArea: "Kennesaw + I-75 northbound",
  },
  {
    id: 120,
    name: "Roswell Premium Repair House",
    address: "38 Hill St",
    city: "Roswell",
    zipCode: "30075",
    coordinates: { latitude: 34.0232, longitude: -84.3616 },
    focus: "luxury",
    serviceArea: "Roswell + Crabapple",
  },
  {
    id: 121,
    name: "Alpharetta EV & Sensor Center",
    address: "2 Park Plaza",
    city: "Alpharetta",
    zipCode: "30009",
    coordinates: { latitude: 34.0754, longitude: -84.2941 },
    focus: "ev",
    serviceArea: "Alpharetta + Avalon tech corridor",
  },
  {
    id: 122,
    name: "Johns Creek Family Auto Body",
    address: "11360 Lakefield Dr",
    city: "Johns Creek",
    zipCode: "30097",
    coordinates: { latitude: 34.0289, longitude: -84.1986 },
    focus: "claims",
    serviceArea: "Johns Creek + Medlock Bridge",
  },
  {
    id: 123,
    name: "Duluth Claims Ready Collision",
    address: "3167 Main St",
    city: "Duluth",
    zipCode: "30096",
    coordinates: { latitude: 34.0029, longitude: -84.1446 },
    focus: "collision",
    serviceArea: "Duluth + Gwinnett spine",
  },
  {
    id: 124,
    name: "Peachtree Corners Mobility Repair",
    address: "310 Technology Pkwy",
    city: "Peachtree Corners",
    zipCode: "30092",
    coordinates: { latitude: 33.9699, longitude: -84.2215 },
    focus: "ev",
    serviceArea: "Peachtree Corners + Norcross tech campuses",
  },
];
