import type { ShopProfile } from "./marketIntelligence";

export const CORE_SHOPS: ShopProfile[] = [
  {
    id: 1,
    name: "Express Auto Body",
    rating: 4.8,
    reviews: 124,
    distanceMiles: 2.4,
    distanceLabel: "2.4 miles",
    certifications: ["ASE Certified", "I-CAR Gold Class"],
    specialties: ["Collision Repair", "Paintless Dent Removal", "Insurance Claims"],
    supportedVehicleTypes: ["Daily Driver", "Fleet", "SUV"],
    supportedMakes: ["Toyota", "Honda", "Ford", "Chevrolet"],
    insurerPrograms: ["State Farm", "Geico", "Progressive"],
    averagePriceLabel: "$850",
    averagePriceValue: 850,
    completionRate: 98,
    responseTimeHours: 2,
    responseTimeLabel: "< 2 hours",
    image:
      "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    categoryRatings: {
      quality: 4.9,
      service: 4.7,
      timeliness: 4.8,
      value: 4.6,
    },
    capabilityTags: ["collision", "pdr", "insurance-approved", "fast-intake"],
    serviceArea: "Central city + inner suburbs",
    capacityBand: "balanced",
    aiSummary: "Strong all-around collision shop with quick intake and broad insurer familiarity.",
  },
  {
    id: 2,
    name: "Premium Collision Center",
    rating: 4.7,
    reviews: 91,
    distanceMiles: 3.8,
    distanceLabel: "3.8 miles",
    certifications: ["Tesla Certified", "BMW Certified", "Aluminum Repair"],
    specialties: ["Luxury Vehicle Repair", "Frame Straightening", "ADAS Calibration"],
    supportedVehicleTypes: ["Luxury", "EV", "SUV"],
    supportedMakes: ["Tesla", "BMW", "Mercedes-Benz", "Audi"],
    insurerPrograms: ["Progressive", "Allstate", "Liberty Mutual"],
    averagePriceLabel: "$925",
    averagePriceValue: 925,
    completionRate: 95,
    responseTimeHours: 3,
    responseTimeLabel: "< 3 hours",
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    categoryRatings: {
      quality: 4.8,
      service: 4.6,
      timeliness: 4.5,
      value: 4.4,
    },
    capabilityTags: ["luxury", "ev", "adas", "frame"],
    serviceArea: "Metro-wide",
    capacityBand: "balanced",
    aiSummary:
      "Best fit for premium brands, EV work, and structural repairs that need calibration.",
  },
  {
    id: 3,
    name: "Value Auto Repair",
    rating: 4.3,
    reviews: 67,
    distanceMiles: 1.5,
    distanceLabel: "1.5 miles",
    certifications: ["AAA Approved"],
    specialties: ["Budget Repairs", "Insurance Claims", "Bumper Work"],
    supportedVehicleTypes: ["Daily Driver", "Compact", "Sedan"],
    supportedMakes: ["Toyota", "Honda", "Nissan", "Hyundai"],
    insurerPrograms: ["Geico", "State Farm"],
    averagePriceLabel: "$675",
    averagePriceValue: 675,
    completionRate: 92,
    responseTimeHours: 4,
    responseTimeLabel: "< 4 hours",
    image:
      "https://images.unsplash.com/photo-1666919643134-d97687c1826c?auto=format&fit=crop&w=800&q=80",
    categoryRatings: {
      quality: 4.1,
      service: 4.3,
      timeliness: 4.0,
      value: 4.7,
    },
    capabilityTags: ["budget", "claim-friendly", "daily-driver"],
    serviceArea: "North side neighborhoods",
    capacityBand: "high-capacity",
    aiSummary:
      "Good budget-oriented match when price sensitivity matters more than boutique service.",
  },
  {
    id: 4,
    name: "Elite Auto Works",
    rating: 4.9,
    reviews: 203,
    distanceMiles: 5.2,
    distanceLabel: "5.2 miles",
    certifications: ["Mercedes Certified", "Porsche Approved", "Jaguar Land Rover Authorized"],
    specialties: ["Exotic Cars", "Custom Paint", "Concierge Pickup"],
    supportedVehicleTypes: ["Luxury", "Exotic", "Collector"],
    supportedMakes: ["Porsche", "Mercedes-Benz", "Ferrari", "Lamborghini"],
    insurerPrograms: ["Chubb", "Progressive", "Nationwide"],
    averagePriceLabel: "$1,250",
    averagePriceValue: 1250,
    completionRate: 99,
    responseTimeHours: 1,
    responseTimeLabel: "< 1 hour",
    image:
      "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=800&q=80",
    categoryRatings: {
      quality: 5.0,
      service: 4.9,
      timeliness: 4.8,
      value: 4.5,
    },
    capabilityTags: ["luxury", "exotic", "concierge", "premium-paint"],
    serviceArea: "Regional luxury corridor",
    capacityBand: "boutique",
    aiSummary:
      "High-touch option for luxury and exotic vehicles where finish quality matters most.",
  },
  {
    id: 5,
    name: "Metro ADAS & EV Center",
    rating: 4.8,
    reviews: 88,
    distanceMiles: 4.1,
    distanceLabel: "4.1 miles",
    certifications: ["Rivian Certified", "Tesla Certified", "ADAS Calibration Lab"],
    specialties: ["EV Structural Repair", "Sensor Calibration", "Battery Safety Checks"],
    supportedVehicleTypes: ["EV", "Luxury", "Fleet"],
    supportedMakes: ["Tesla", "Rivian", "Lucid", "Hyundai"],
    insurerPrograms: ["Progressive", "USAA", "Allstate"],
    averagePriceLabel: "$1,050",
    averagePriceValue: 1050,
    completionRate: 96,
    responseTimeHours: 2,
    responseTimeLabel: "< 2 hours",
    image:
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80",
    categoryRatings: {
      quality: 4.9,
      service: 4.6,
      timeliness: 4.7,
      value: 4.3,
    },
    capabilityTags: ["ev", "adas", "calibration", "structural"],
    serviceArea: "Metro + airport corridor",
    capacityBand: "balanced",
    aiSummary:
      "Best technical fit for EV repairs, sensor recalibration, and modern vehicle electronics.",
  },
  {
    id: 6,
    name: "Hail & Dent Rescue",
    rating: 4.6,
    reviews: 149,
    distanceMiles: 3.2,
    distanceLabel: "3.2 miles",
    certifications: ["PDR Nation Member", "I-CAR Platinum Individual"],
    specialties: ["Hail Damage", "Paintless Dent Removal", "Mobile Estimates"],
    supportedVehicleTypes: ["Daily Driver", "Truck", "SUV"],
    supportedMakes: ["Ford", "Chevrolet", "Toyota", "Ram"],
    insurerPrograms: ["State Farm", "Farmers Insurance", "Nationwide"],
    averagePriceLabel: "$720",
    averagePriceValue: 720,
    completionRate: 97,
    responseTimeHours: 1,
    responseTimeLabel: "< 1 hour",
    image:
      "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?auto=format&fit=crop&w=800&q=80",
    categoryRatings: {
      quality: 4.7,
      service: 4.8,
      timeliness: 4.9,
      value: 4.6,
    },
    capabilityTags: ["hail", "pdr", "mobile-estimate", "fast-turn"],
    serviceArea: "County-wide storm response",
    capacityBand: "high-capacity",
    aiSummary:
      "Fastest hail and dent specialist, especially strong when volume spikes after storms.",
  },
  {
    id: 7,
    name: "Fleet & Commercial Bodyworks",
    rating: 4.5,
    reviews: 75,
    distanceMiles: 6.5,
    distanceLabel: "6.5 miles",
    certifications: ["ASE Certified", "Commercial Fleet Partner"],
    specialties: ["Fleet Repair", "Heavy-Duty Collision", "Box Truck Body Work"],
    supportedVehicleTypes: ["Fleet", "Commercial", "Truck"],
    supportedMakes: ["Ford", "Chevrolet", "Ram", "Freightliner"],
    insurerPrograms: ["Nationwide", "Liberty Mutual", "Travelers"],
    averagePriceLabel: "$1,180",
    averagePriceValue: 1180,
    completionRate: 94,
    responseTimeHours: 2,
    responseTimeLabel: "< 2 hours",
    image:
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80",
    categoryRatings: {
      quality: 4.6,
      service: 4.4,
      timeliness: 4.5,
      value: 4.4,
    },
    capabilityTags: ["fleet", "commercial", "truck", "high-capacity"],
    serviceArea: "Industrial belt + regional routes",
    capacityBand: "high-capacity",
    aiSummary:
      "Best operational fit for fleets, work trucks, and insurers managing commercial volume.",
  },
  {
    id: 8,
    name: "Glass, Alignment & Refinish Hub",
    rating: 4.4,
    reviews: 112,
    distanceMiles: 2.8,
    distanceLabel: "2.8 miles",
    certifications: ["Safelite Partner", "Hunter Alignment Certified"],
    specialties: ["Auto Glass", "Wheel Alignment", "Refinish Blending"],
    supportedVehicleTypes: ["Daily Driver", "SUV", "Luxury"],
    supportedMakes: ["Toyota", "Honda", "Subaru", "BMW"],
    insurerPrograms: ["Geico", "Allstate", "Liberty Mutual"],
    averagePriceLabel: "$790",
    averagePriceValue: 790,
    completionRate: 93,
    responseTimeHours: 3,
    responseTimeLabel: "< 3 hours",
    image:
      "https://images.unsplash.com/photo-1486496572940-2bb2341fdbdf?auto=format&fit=crop&w=800&q=80",
    categoryRatings: {
      quality: 4.4,
      service: 4.5,
      timeliness: 4.6,
      value: 4.3,
    },
    capabilityTags: ["glass", "alignment", "refinish", "supplemental"],
    serviceArea: "City ring + nearby commuter towns",
    capacityBand: "balanced",
    aiSummary:
      "Useful specialist for glass, alignment, and finish work paired with collision claims.",
  },
];
