import type { Coordinates } from "../../types/mapDomain";

export type NYMetroHubFocus =
  | "collision"
  | "luxury"
  | "pdr"
  | "ev"
  | "fleet"
  | "refinish"
  | "hail"
  | "claims";

export type NYMetroHubSeed = {
  id: number;
  name: string;
  address: string;
  city: string;
  zipCode: string;
  coordinates: Coordinates;
  focus: NYMetroHubFocus;
  serviceArea: string;
};

export const NY_METRO_HUB_IMAGES = [
  "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1666919643134-d97687c1826c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
];

export const NY_METRO_HUB_SEEDS: NYMetroHubSeed[] = [
  {
    id: 101,
    name: "Downtown White Plains Collision Center",
    address: "55 Court St",
    city: "White Plains",
    zipCode: "10601",
    coordinates: { latitude: 41.034, longitude: -73.763 },
    focus: "collision",
    serviceArea: "White Plains central + Westchester Govt Ctr",
  },
  {
    id: 102,
    name: "Yonkers Express Auto Body",
    address: "975 Central Park Ave",
    city: "Yonkers",
    zipCode: "10704",
    coordinates: { latitude: 40.937, longitude: -73.892 },
    focus: "claims",
    serviceArea: "Yonkers + Cross County corridor",
  },
  {
    id: 103,
    name: "New Rochelle Precision Repair",
    address: "140 Main St",
    city: "New Rochelle",
    zipCode: "10801",
    coordinates: { latitude: 40.912, longitude: -73.782 },
    focus: "collision",
    serviceArea: "New Rochelle + Pelham",
  },
  {
    id: 104,
    name: "Tarrytown Luxury Bodyworks",
    address: "50 S Broadway",
    city: "Tarrytown",
    zipCode: "10591",
    coordinates: { latitude: 41.076, longitude: -73.859 },
    focus: "luxury",
    serviceArea: "Tarrytown + Irvington + Sleepy Hollow",
  },
  {
    id: 105,
    name: "Mount Kisco PDR Studio",
    address: "195 N Bedford Rd",
    city: "Mount Kisco",
    zipCode: "10549",
    coordinates: { latitude: 41.209, longitude: -73.724 },
    focus: "pdr",
    serviceArea: "Mount Kisco + Bedford",
  },
  {
    id: 106,
    name: "Nyack Frame & Paint",
    address: "80 Main St",
    city: "Nyack",
    zipCode: "10960",
    coordinates: { latitude: 41.091, longitude: -73.919 },
    focus: "refinish",
    serviceArea: "Nyack + Upper Grandview",
  },
  {
    id: 107,
    name: "Spring Valley Direct Repair",
    address: "10 Memorial Dr",
    city: "Spring Valley",
    zipCode: "10977",
    coordinates: { latitude: 41.113, longitude: -74.044 },
    focus: "claims",
    serviceArea: "Spring Valley + Nanuet",
  },
  {
    id: 108,
    name: "Poughkeepsie Claims Hub",
    address: "250 Main Mall",
    city: "Poughkeepsie",
    zipCode: "12601",
    coordinates: { latitude: 41.694, longitude: -73.921 },
    focus: "claims",
    serviceArea: "City of Poughkeepsie + Dutchess core",
  },
  {
    id: 109,
    name: "Beacon ADAS & EV Center",
    address: "8 Beekman St",
    city: "Beacon",
    zipCode: "12508",
    coordinates: { latitude: 41.505, longitude: -73.97 },
    focus: "ev",
    serviceArea: "Beacon + Fishkill east bank",
  },
  {
    id: 110,
    name: "Garden City Dent Center",
    address: "100 Seventh St",
    city: "Garden City",
    zipCode: "11530",
    coordinates: { latitude: 40.727, longitude: -73.634 },
    focus: "pdr",
    serviceArea: "Garden City + Mineola",
  },
  {
    id: 111,
    name: "Great Neck Premium Auto Body",
    address: "22 Middle Neck Rd",
    city: "Great Neck",
    zipCode: "11021",
    coordinates: { latitude: 40.801, longitude: -73.728 },
    focus: "luxury",
    serviceArea: "Great Neck + Manhasset",
  },
  {
    id: 112,
    name: "Newburgh Storm Repair",
    address: "15 Liberty St",
    city: "Newburgh",
    zipCode: "12550",
    coordinates: { latitude: 41.503, longitude: -74.01 },
    focus: "hail",
    serviceArea: "Newburgh + New Windsor",
  },
  {
    id: 113,
    name: "Middletown Fleet & Commercial",
    address: "200 Route 211 E",
    city: "Middletown",
    zipCode: "10940",
    coordinates: { latitude: 41.451, longitude: -74.392 },
    focus: "fleet",
    serviceArea: "Middletown + Goshen + Chester",
  },
  {
    id: 114,
    name: "Carmel Quick Intake Collision",
    address: "65 McAlpin Ave",
    city: "Carmel",
    zipCode: "10512",
    coordinates: { latitude: 41.432, longitude: -73.68 },
    focus: "collision",
    serviceArea: "Carmel + Mahopac",
  },
  {
    id: 115,
    name: "Cold Spring Refinish Works",
    address: "10 Kemble Ave",
    city: "Cold Spring",
    zipCode: "10516",
    coordinates: { latitude: 41.417, longitude: -73.958 },
    focus: "refinish",
    serviceArea: "Cold Spring + Garrison",
  },
  {
    id: 116,
    name: "Scarsdale Calibration Garage",
    address: "800 Scarsdale Ave",
    city: "Scarsdale",
    zipCode: "10583",
    coordinates: { latitude: 41.005, longitude: -73.787 },
    focus: "ev",
    serviceArea: "Scarsdale + Eastchester",
  },
  {
    id: 117,
    name: "Mamaroneck Claims Concierge",
    address: "325 Mamaroneck Ave",
    city: "Mamaroneck",
    zipCode: "10543",
    coordinates: { latitude: 40.949, longitude: -73.734 },
    focus: "claims",
    serviceArea: "Mamaroneck + Larchmont",
  },
  {
    id: 118,
    name: "Rye EV & Sensor Center",
    address: "102 Purchase St",
    city: "Rye",
    zipCode: "10580",
    coordinates: { latitude: 40.981, longitude: -73.683 },
    focus: "ev",
    serviceArea: "Rye + Port Chester",
  },
  {
    id: 119,
    name: "Nanuet Claims Ready Collision",
    address: "140 Market St",
    city: "Nanuet",
    zipCode: "10954",
    coordinates: { latitude: 41.089, longitude: -74.014 },
    focus: "collision",
    serviceArea: "Nanuet + Pearl River",
  },
  {
    id: 120,
    name: "Haverstraw Auto Body",
    address: "35 New Main St",
    city: "Haverstraw",
    zipCode: "10927",
    coordinates: { latitude: 41.198, longitude: -73.968 },
    focus: "collision",
    serviceArea: "Haverstraw + West Haverstraw",
  },
  {
    id: 121,
    name: "Fishkill Family Auto Body",
    address: "860 Route 9",
    city: "Fishkill",
    zipCode: "12524",
    coordinates: { latitude: 41.534, longitude: -73.899 },
    focus: "claims",
    serviceArea: "Fishkill + Wappingers Falls",
  },
  {
    id: 122,
    name: "Rhinebeck Hail Repair",
    address: "6 Mill St",
    city: "Rhinebeck",
    zipCode: "12572",
    coordinates: { latitude: 41.927, longitude: -73.913 },
    focus: "hail",
    serviceArea: "Rhinebeck + Red Hook",
  },
  {
    id: 123,
    name: "Mineola Fleet Repair Hub",
    address: "55 Mineola Blvd",
    city: "Mineola",
    zipCode: "11501",
    coordinates: { latitude: 40.749, longitude: -73.64 },
    focus: "fleet",
    serviceArea: "Mineola + Westbury",
  },
  {
    id: 124,
    name: "Hempstead Express Collision",
    address: "100 N Franklin St",
    city: "Hempstead",
    zipCode: "11550",
    coordinates: { latitude: 40.706, longitude: -73.619 },
    focus: "collision",
    serviceArea: "Hempstead + Uniondale",
  },
];
